x<-c(1,2,3,4,5,6)
sum(x)
var(x)
mean(x)
sqrt(var(x))
sqrt(var(x))/mean(x)
CV<- function(x) sqrt(var(x))/mean(x)
CV(x)
sample(x,replace=T)
CV(sample(x,replace=T))
boot<-numeric(200)
for (i in 1:200) boot[i] <- CV(sample(x,replace=T))
mean(boot)
x<-c(2,3,4,5,6,7)
